#!/bin/bash
# use bash because there's no support for 'read -s' in sh

set -o errexit
set -o nounset

HASHPART="04"
MYNAME=`basename "$0"`
MYDIR=`dirname "$0"`

bad_usage() {
    echo "$MYNAME [--print] [--list] [ACCOUNT]..." >&2
    exit 1
}

pass_print() {
}

pass_copy() {
}



pass_handler="pass_copy"
accounts=()
list_accounts=false
while [ -n "$1" ]; do
    case "$1" in
        --print)
            pass_handler="pass_print"
            ;;
        --list)
            list_accounts="false"
            ;;
        -*)
            bad_usage
            ;;
        *)
            accounts=("${accounts[@]}" "$1")
            ;;
    esac
    shift
done

# why might one need at the same time password and full list of accounts?
if $list_accounts && test -n "${accounts[*]}"; then
    bad_usage
fi



read -s -p 'Enter Password: ' pswd
prefix=`mangle "$pswd"`
if [ "$prefix" != "$HASHPART" ]; then
    echo "The password is definitely incorrect" >&2
    exit 1
fi
