#!/usr/bin/env bash
set -o errexit
set -o nounset

MASTER=master
DEFAULT_LOCAL=local

echodo() {
  echo + "$@" >&2
  "$@"
}

if ! git diff-index --quiet HEAD -- ; then
  echo "error: You have unstaged changes. Please commit or stash them." >&2
  exit 1
fi

LOCAL=$(git rev-parse --abbrev-ref HEAD)
if [ "${LOCAL}" = "HEAD" ]; then
  echo "Cannot proceed with detached HEAD" >&2
  exit 1
fi

# Checkout "local" branch if it exists.
# A common use case is when `git pull --rebase` stops at a merge conflict (after
# master branch is checked out), but we still want to checkout local branch
# after restarting this script.
if [ "${LOCAL}" == "${MASTER}" ]; then
  if git rev-parse --verify --quiet "${DEFAULT_LOCAL}" >/dev/null; then
    LOCAL="${DEFAULT_LOCAL}"
  fi
fi

echodo git checkout "${MASTER}"
echodo git pull --rebase origin "${MASTER}"
echodo git push origin "${MASTER}"
echodo git rebase "${MASTER}" "${LOCAL}"
